name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/wled-backup:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/wled-backup:${{ github.sha }}

  package-image:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull the pushed image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/wled-backup:latest

      - name: Save image to tar.gz
        run: |
          docker save ${{ secrets.DOCKERHUB_USERNAME }}/wled-backup:latest \
            | gzip > wled-backup.tar.gz

      - name: Upload Unraid package artifact
        uses: actions/upload-artifact@v3
        with:
          name: wled-backup-unraid-package
          path: wled-backup.tar.gz
